### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by AwkwardLefty** [evolvio/evolv.io#16] opened 2016-10-04 00:42 UTC
whenever I try to run this program I get a little gray box and it does't work at all

**Comment by YoYoYonnY** [comment] 2016-10-04 20:27
Cannot reproduce, closing.

**Comment by YoYoYonnY** [comment] 2016-10-04 20:28
@AwkwardLefty The [README](https://github.com/evolvio/evolv.io/blob/master/README.md) file now includes instructions on how to execute evolv.io:

**Closed by YoYoYonnY** 2016-10-04 20:27 UTC
Labels: wontfix
